#!/usr/bin/env bash
# Embed the static gadget files into a generated Swift source file so the
# resulting binary is fully self-contained (no external resource bundle).
#
# Run from the app/ directory: ./tools/generate-assets.sh
set -euo pipefail

cd "$(dirname "$0")/.."          # -> app/
ROOT="$(cd .. && pwd)"           # repo root holding index.html, assets/, ...
OUT="Sources/GadgetsApp/Assets.generated.swift"

# Web files to embed, as paths relative to the repo root. These mirror what the
# nginx Dockerfile ships.
FILES=(
  "index.html"
  "assets/common.css"
  "markdown/index.html"
  "json/index.html"
  "code/index.html"
  "log/index.html"
)

{
  echo "// AUTO-GENERATED by tools/generate-assets.sh — do not edit by hand."
  echo "// Regenerate with: make assets"
  echo "//"
  echo "// Maps a web path (e.g. \"markdown/index.html\") to its base64-encoded bytes."
  echo "let embeddedAssets: [String: String] = ["
  for rel in "${FILES[@]}"; do
    src="$ROOT/$rel"
    if [[ ! -f "$src" ]]; then
      echo "  ERROR: missing $src" >&2
      exit 1
    fi
    b64="$(base64 < "$src" | tr -d '\n')"
    echo "  \"$rel\": \"$b64\","
  done
  echo "]"
} > "$OUT"

echo "Wrote $OUT (${#FILES[@]} files embedded)"
